
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "banque_service", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "conversion_euro_to_dh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversion_euro_to_dh", targetNamespace = "http://ws/", className = "proxy.ConversionEuroToDh")
    @ResponseWrapper(localName = "conversion_euro_to_dhResponse", targetNamespace = "http://ws/", className = "proxy.ConversionEuroToDhResponse")
    @Action(input = "http://ws/banque_service/conversion_euro_to_dhRequest", output = "http://ws/banque_service/conversion_euro_to_dhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://ws/", className = "proxy.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://ws/", className = "proxy.GetcompteResponse")
    @Action(input = "http://ws/banque_service/getcompteRequest", output = "http://ws/banque_service/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcomptes", targetNamespace = "http://ws/", className = "proxy.Getcomptes")
    @ResponseWrapper(localName = "getcomptesResponse", targetNamespace = "http://ws/", className = "proxy.GetcomptesResponse")
    @Action(input = "http://ws/banque_service/getcomptesRequest", output = "http://ws/banque_service/getcomptesResponse")
    public List<Compte> getcomptes();

}
